#!/bin/bash
#
# contextAdapter         Start/Stop the Generic Context Adapter
#
# chkconfig: 2345 99 60
# description: Generic Context Adapter for Telefonica's IoT Platform
### BEGIN INIT INFO
# Provides: contextAdapter
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  345
# Default-Stop: 90
# Short-Description: run contextAdapter
# Description: The Generica Context Adapter is a bridge between Third party protocols
# protocol and the NGSI protocol used internally by Telefonica's IoT Platform.
### END INIT INFO

# Copyright 2015 Telefonica Investigacion y Desarrollo, S.A.U
#
# This file is part of the context-adapter.
#
# the context-adapter is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# the context-adapter is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with the context-adapter. If not, see http://www.gnu.org/licenses/.
#
# For those usages not covered by this license please contact with
# iot_support at tid dot es

. /etc/rc.d/init.d/functions

PARAM=$1
NAME=context-adapter
EXECUTABLE=bin/context-adapter
CA_PATH=/opt/contextAdapter
PIDFILE=$CA_PATH/$NAME.pid
LOG_PATH=/var/log/contextAdapter/contextAdapter.log

ca_start()
{
    printf "%-50s" "Starting ${NAME}..."
    cd $CA_PATH
    if [[ -x ${EXECUTABLE} ]]; then
        cd $CA_PATH
        su $CA_USER -c "cd $CA_PATH; nohup ${EXECUTABLE} &>> $LOG_PATH & echo \$! > $PIDFILE"
        echo "Success"
    else
        printf "%s\n" "Fail - missing ${EXECUTABLE} executable"
        exit 1
    fi
}

ca_stop()
{
    printf "%-50s" "Stopping $NAME..."
    if [ -f "${PIDFILE}" ]; then
        kill -9 $(cat ${PIDFILE})
        rm -f ${PIDFILE}
        printf "%s\n" "$(success)"
    else
        printf "%s\n" "$(failure)"
    fi
}

ca_status()
{
    status -p ${PIDFILE} ${EXECUTABLE}
}

case ${PARAM} in

    'start')
        echo "Starting..."
        status -p ${PIDFILE} ${EXECUTABLE} && exit 0
        ca_start
        ;;

    'stop')
        echo "Stopping..."
        status -p ${PIDFILE} ${EXECUTABLE} || exit 0
        ca_stop
        ;;

    'restart')
        ca_stop
        ca_start
        ;;

    'status')
        ca_status
        ;;

esac
